/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native_Input */

#ifndef _Included_Native_Input
#define _Included_Native_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_Input
 * Method:    check
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Native_Input_check
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
